/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab1;

import lab1.domain.Questionnaire;
import lab1.domain.Result;
import lab1.domain.Student;
import lab1.service.*;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext("./spring-config.xml");
        StudentService studentService =  context.getBean(StudentService.class);
        Student student = studentService.register();

        QuestionnaireService questionnaireService = context.getBean(QuestionnaireService.class);
        try {
            Questionnaire questionnaire = questionnaireService.findByName("name");

            InquirerService inquirerService = context.getBean(InquirerService.class);
            Result result = inquirerService.makeInquirer(student, questionnaire);

            ScoringService scoringService = context.getBean(ScoringService.class);
            System.out.println(scoringService.evaluate(result));
        } catch (Exception e) {

        }

    }
}
