/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab1;

import lab1.config.DaoConfig;
import lab1.config.GenericConfig;
import lab1.config.ServiceConfig;
import lab1.domain.Result;
import lab1.runner.RunnerService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;


@Configuration
@ComponentScan
public class App {

    final static Logger logger = LoggerFactory.getLogger(App.class);


    public static void main(String[] args) {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
        context.register(DaoConfig.class);
        context.register(ServiceConfig.class);
        context.register(GenericConfig.class);
        context.refresh();

        logger.info("logger app");
        RunnerService inquirerService = context.getBean(RunnerService.class);
        GenericConfig genericConfig = context.getBean(GenericConfig.class);
        try {
            Result result = inquirerService.makeInquirer("name");
            genericConfig.consoleUtil().printLocalizedString("score", new String[] {result.getScore()});
        } catch (Exception e) {
            logger.info(e.getMessage());
        }

    }
}
